#!/usr/bin/env python

# test if barcode in correct production run and passed
# keep up with how many boards found total
# tempSerialTest serialnumber, date time, user


import os
import sys
import traceback
import string
import subprocess
import psycopg2
from colorama import init
from termcolor import colored, cprint
import winsound

# terminal init for windows
init()
goodfrequency = 2500
goodduration = 1000

print ("Test serial for run")
directory = os.path.split(os.path.realpath(__file__))[0]


print ("Connecting to database...")
dbfile = open(directory+'/postgres_info.txt', 'r')
postgresInfo = dbfile.read()
dbfile.close()
try:
  testStorage = psycopg2.connect(postgresInfo)
  print ("Connect success.")
except:
  print ("Could not connect!")
  sys.exit(0)


state = "testing"
runId = '221'
tstuser= '1'

while (state == 'testing'):
  # get serial number from terminal
  print ("Enter serial number : ")
  serialNumber = input()
  if serialNumber == 'exit':
    sys.exit(0)
	
  conn = psycopg2.connect(postgresInfo)
  cur = conn.cursor()
  
  cur.execute("""SELECT serial FROM testdata WHERE productionrunid = %s AND testresults LIKE 'Passed' AND serial = %s""",(runId,serialNumber))
  rows = cur.fetchall()
  runcount = len(rows)
#  runcount = int(cur.fetchone()[0])
  	

 
  #print(runcount)
  
  # print results
  if runcount > 0:
    # check for found in already found boards
    cur.execute("""SELECT serialnumber FROM tempserialtest WHERE serialnumber = %s""",(serialNumber,))
    rows = cur.fetchall()
    foundcount = len(rows)
    if foundcount > 0:
      # board already in found table
      print (colored("Error! Already Found and in table!!!!",'white','on_yellow'))
      winsound.Beep(500, 2000)
      winsound.Beep(800, 2000)
      conn.commit
      cur.close()
	
    else:
    # write found result to temp table
      insertquery = """INSERT INTO tempserialtest (serialnumber, tstuser) VALUES (%s, %s)"""
      cur.execute(insertquery,(serialNumber,tstuser))
      conn.commit()
      conn.close()

      print (colored("Found",'white','on_green'))
#      winsound.Beep(goodfrequency, goodduration)
      winsound.Beep(2500, 1500)
#      winsound.Beep(2500, 1000)

  else:
    print (colored("Not Found!!!!",'white','on_red'))
    winsound.Beep(800, 2000)
    winsound.Beep(500, 2000)
    conn.commit
    cur.close()

  

#	cursor.execute("""SELECT date FROM finishedgoodstracking WHERE date = %s""",(dateTest,))
#	rows = cursor.fetchall()
#	if len(rows) > 0:
#		cursor.execute("""UPDATE finishedgoodstracking SET minirambos=%s, rambos=%s, total=%s WHERE date=%s""",(miniNum,ramboNum,total,dateTest))
#	else:
#		cursor.execute("""INSERT INTO finishedgoodstracking(date,minirambos,rambos,total) VALUES(%s::date,%s,%s,%s)""",(dateTest,miniNum,ramboNum,total))
#	testStorage.commit()



 # SELECT COUNT(DISTINCT serial) FROM testdata WHERE productionrunid = 221 and testresults LIKE 'Passed'